version: 0.2

phases:
  build:
    commands:
      - echo "CodePipelineが自動でデプロイするため、aws deployコマンドは不要です"
      # ※ もしビルドに必要なコマンド（例: npm run build やコンパイルなど）があればここに書きます。
      # なければ echo だけで空欄でも大丈夫です。

artifacts:
  files:
    - '**/*'
  base-directory: src